### ISSUE TITLE
Feature Request: `dom.text()` should Normalize Whitespace

### ISSUE THREAD

**Issue by jdalt** [jdalt/angular-test-tool-box#2]
Most of the time we grab `dom.text()` we want the text to reflect what the user sees in the browser.  If `dom.text()` can normalize text (while being overriden to get raw text) it will make testing easier and consistent.

This will be a breaking change and require a major version bump.

**Comment by ScottTrenda** [comment]
Potential implementation:
```
      text: function(selector, nth, skipNormalization) {
        var el = root
        if(selector) el = root.find(selector)
        if(nth != null) el = el.eq(nth)
        return skipNormalization ? el.text() : el.text().replace(/\s+/g, ' ').trim()
      }
```

**Comment by jdalt** [comment]
Implemented in https://github.com/jdalt/angular-test-tool-box/pull/3
